<?php
/**
 * Delivery-note engine.
 * A delivery note moves stock from a source location (usually the main store)
 * to the destination site store, and posts paired TRANSFER_OUT / TRANSFER_IN
 * movement rows once the document is issued or received.
 */
require_once __DIR__ . '/../helpers.php';

/** Remove every movement generated by a delivery note, restoring balances. */
function clear_dn_movements(int $dnId): int
{
    $legs = fetch_all('SELECT * FROM movements WHERE dn_id = ? ORDER BY id DESC', [$dnId]);
    foreach ($legs as $leg) {
        reverse_movement_effect($leg);
    }
    if ($legs) {
        q('DELETE FROM movements WHERE dn_id = ?', [$dnId]);
    }
    return count($legs);
}

/**
 * Post the stock movements for a delivery note.
 * Called inside an existing transaction by the caller.
 */
function post_dn_movements(array $dn, array $lines): int
{
    if (in_array($dn['status'], ['draft', 'cancelled'], true)) {
        return 0;   // no stock effect for draft / cancelled documents
    }
    $from = (int)$dn['from_project_id'];
    $to   = (int)$dn['project_id'];
    if ($from === $to) {
        throw new RuntimeException('The source and destination stores must be different.');
    }
    $created = 0;
    foreach ($lines as $ln) {
        $item = fetch_one('SELECT * FROM items WHERE id = ?', [(int)$ln['item_id']]);
        if (!$item) {
            throw new RuntimeException('Item #' . $ln['item_id'] . ' no longer exists.');
        }
        $qty = (float)$ln['quantity'];
        if ($qty <= 0) {
            continue;
        }
        $base = [
            'company_id' => (int)$dn['company_id'],
            'item_id' => (int)$item['id'],
            'quantity' => $qty,
            'uom' => $item['uom'],
            'unit_cost' => (float)$item['unit_cost'],
            'supplier_id' => $dn['supplier_id'] ?: null,
            'dn_id' => (int)$dn['id'],
            'transfer_ref' => $dn['dn_no'],
            'reference' => $dn['dn_no'],
            'movement_date' => $dn['dn_date'],
            'notes' => 'Delivered to site against ' . $dn['dn_no'],
        ];

        record_movement($base + ['movement_type' => 'TRANSFER_OUT', 'project_id' => $from,
            'from_project_id' => $from, 'to_project_id' => $to]);
        record_movement($base + ['movement_type' => 'TRANSFER_IN', 'project_id' => $to,
            'from_project_id' => $from, 'to_project_id' => $to,
            'notes' => 'Received at site store against ' . $dn['dn_no']]);
        $created += 2;
    }
    return $created;
}

/** Recompute the destination store revenue / total value of a delivery note. */
function dn_totals(array $lines, array $itemsById): array
{
    $qty = 0.0;
    $val = 0.0;
    foreach ($lines as $ln) {
        $qty += (float)$ln['quantity'];
        $cost = isset($itemsById[(int)$ln['item_id']]) ? (float)$itemsById[(int)$ln['item_id']]['unit_cost'] : 0.0;
        $val += (float)$ln['quantity'] * $cost;
    }
    return [round($qty, 3), round($val, 2)];
}
